// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWs3m_l4v-mcKKGV916lDHjTT81ahY_J4',
    appId: '1:961765693578:web:57e97e1e051c6daef53573',
    messagingSenderId: '961765693578',
    projectId: 'product-catalog-779fa',
    authDomain: 'product-catalog-779fa.firebaseapp.com',
    storageBucket: 'product-catalog-779fa.appspot.com',
    measurementId: 'G-XXELKXQGL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRoowAaxQE-iMF04aTDcGexyMZ8YhB80M',
    appId: '1:961765693578:android:a3280927adee6b9cf53573',
    messagingSenderId: '961765693578',
    projectId: 'product-catalog-779fa',
    storageBucket: 'product-catalog-779fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc23H2tcS_Q0LldjP4TNQfqS7liYElR4k',
    appId: '1:961765693578:ios:ee0fc53bc25fa1def53573',
    messagingSenderId: '961765693578',
    projectId: 'product-catalog-779fa',
    storageBucket: 'product-catalog-779fa.appspot.com',
    iosBundleId: 'com.example.productCatalogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc23H2tcS_Q0LldjP4TNQfqS7liYElR4k',
    appId: '1:961765693578:ios:ee0fc53bc25fa1def53573',
    messagingSenderId: '961765693578',
    projectId: 'product-catalog-779fa',
    storageBucket: 'product-catalog-779fa.appspot.com',
    iosBundleId: 'com.example.productCatalogApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWs3m_l4v-mcKKGV916lDHjTT81ahY_J4',
    appId: '1:961765693578:web:bfbc6369057253bff53573',
    messagingSenderId: '961765693578',
    projectId: 'product-catalog-779fa',
    authDomain: 'product-catalog-779fa.firebaseapp.com',
    storageBucket: 'product-catalog-779fa.appspot.com',
    measurementId: 'G-V6C25H3F16',
  );

}